name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-macos:
    name: Build macOS (electron-builder)
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm package:macos --publish=never -c.mac.identity=null
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Clean up builds
        run: rm -rfv dist/mac-universal

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GitChan-dist-mac
          path: dist/
          overwrite: true

  build-windows:
    name: Build Windows (electron-builder)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm package:win --publish=never

      - name: Clean up builds
        run: Remove-Item dist/win-unpacked -Recurse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GitChan-dist-win
          path: dist
          overwrite: true

  build-linux:
    name: Build Linux (electron-builder)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm package:linux --publish=never

      - name: Clean up builds
        run: rm -rfv dist/linux-unpacked

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GitChan-dist-linux
          path: dist
          overwrite: true
